// command/maker/fakestory.js
const fetch = require("node-fetch");
const { loadUser, saveUser } = require("../../handler");

// Escape untuk MarkdownV2 (Telegram)
function escapeMarkdownV2(text = "") {
  return text.replace(/([_*\[\]()~`>#+\-=|{}.!\\])/g, "\\$1");
}

module.exports = async (ctx) => {
  try {
    // Bahasa pengguna
    const lang = (ctx.from?.language_code || "").startsWith("id") ? "id" : "en";

    // Load user dari handler
    const user = loadUser(ctx.from.id, ctx.from.first_name);

    // Cek limit harian
    if (user.limit <= 0) {
      const msg =
        lang === "id"
          ? "🚫 Limit kamu sudah habis. Tunggu 24 jam untuk reset."
          : "🚫 Your daily limit has run out. Please wait 24 hours for reset.";
      return ctx.reply(msg, { reply_to_message_id: ctx.message?.message_id });
    }

    // Ambil argumen: /fakestory <username> <caption...>
    const parts = ctx.message.text.split(" ").slice(1);
    if (!parts.length) {
      const usage =
        lang === "id"
          ? "💡 Gunakan format: /fakestory <username> <caption>\nContoh: `/fakestory logic__vibes Halo guys`"
          : "💡 Use format: /fakestory <username> <caption>\nExample: `/fakestory logic__vibes Hello Guys`";
      return ctx.reply(usage, {
        reply_to_message_id: ctx.message?.message_id,
        parse_mode: "Markdown",
      });
    }

    const username = parts[0];
    const captionText = parts.slice(1).join(" ") || "";

    // Kurangi limit user
    user.limit -= 1;
    saveUser(ctx.from.id, user);

    // Pesan loading
    await ctx.reply(
      lang === "id" ? "🕐 Sedang membuat fake story..." : "🕐 Generating fake story...",
      { reply_to_message_id: ctx.message?.message_id }
    );

    // Ambil avatar profil Telegram user (fallback ke default)
    let avatarUrl = "https://files.catbox.moe/1l6trg.jpg"; // default avatar
    try {
      const photos = await ctx.telegram.getUserProfilePhotos(ctx.from.id, { limit: 1 });
      if (photos.total_count > 0) {
        const fileId = photos.photos[0][0].file_id;
        const file = await ctx.telegram.getFile(fileId);
        avatarUrl = `https://api.telegram.org/file/bot${ctx.telegram.token}/${file.file_path}`;
      }
    } catch (e) {
      console.warn("⚠️ Tidak bisa mengambil foto profil:", e.message || e);
    }

    // Build API URL (Deline endpoint)
    const apiUrl = `https://api.deline.web.id/maker/fakestory?username=${encodeURIComponent(
      username
    )}&caption=${encodeURIComponent(captionText)}&avatar=${encodeURIComponent(avatarUrl)}`;

    const res = await fetch(apiUrl, { headers: { "User-Agent": "Mozilla/5.0" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const contentType = res.headers.get("content-type") || "";
    if (!contentType.includes("image")) {
      let txt;
      try {
        txt = await res.text();
      } catch {
        txt = "<non-text response>";
      }
      throw new Error(`API tidak mengembalikan gambar. Response: ${txt}`);
    }

    const imageBuffer = Buffer.from(await res.arrayBuffer());

    // Caption yang dikirim bersama foto
    const captionLines = [
      `👤 ${escapeMarkdownV2(username)}`,
      captionText ? `💬 ${escapeMarkdownV2(captionText)}` : null,
      `📦 ${escapeMarkdownV2("Tifa Bot - Fake Story")}`,
      `✍️ ${escapeMarkdownV2("Generated by Bot")}`,
    ]
      .filter(Boolean)
      .join("\n");

    // Kirim foto hasil sebagai gambar
    await ctx.replyWithPhoto(
      { source: imageBuffer },
      {
        caption: captionLines,
        parse_mode: "MarkdownV2",
        reply_to_message_id: ctx.message?.message_id,
      }
    );
  } catch (err) {
    console.error("❌ Error di fakestory.js:", err);
    const msg =
      (ctx.from?.language_code || "").startsWith("id")
        ? "❌ Terjadi kesalahan saat membuat fake story 😥"
        : "❌ An error occurred while generating the fake story 😥";
    await ctx.reply(msg, { reply_to_message_id: ctx.message?.message_id });
  }
};
